update(security): Ubuntu to alpine, update go pkgs
StatCan/goofys pull request #6
Opened 2024-08-23 15:39 UTC by bryanpaget

The Ubuntu image had some vulnerablities and the easiest way to fix it was to switch to alpine. This results in a smaller image with fewer attack surfaces. Since this is a small image with a single application it makes sense to use a small base.

I've also updated some of the go packages, see the diff.

2024-08-28 16:47 UTC, bryanpaget commented
Since we ran into an issue with bash, I have added bash to the container in order to maximize compatibility since we were previously calling bash from the Ubuntu-based version of this goofys container.

2024-08-30 16:31 UTC, bryanpaget commented
I tested this on dev by using a custom deployment provided by @mathis-marcotte, using this goofys image. I was able to shell into the running container and I was able to verify that the volume was being mounted as expected:

![image](https://github.com/user-attachments/assets/46ec3e67-7af7-494f-bf80-606405705033)

2024-09-04 18:42 UTC, bryanpaget commented
Some new CVEs have popped up but adding apk update && apk upgrade to the Dockerfile ensures we are using the latest and most secure packages.

goofys (alpine 3.20.2)

Total: 2 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 0, CRITICAL: 0)

┌────────────┬───────────────┬──────────┬────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────┐
│  Library   │ Vulnerability │ Severity │ Status │ Installed Version │ Fixed Version │                          Title                          │
├────────────┼───────────────┼──────────┼────────┼───────────────────┼───────────────┼─────────────────────────────────────────────────────────┤
│ libcrypto3 │ https://github.com/advisories/GHSA-7m4m-pwhv-49c5 │ MEDIUM   │ fixed  │ 3.3.1-r3          │ 3.3.2-r0      │ Issue summary: Applications performing certificate name │
│            │               │          │        │                   │               │ checks (e.g., ...                                       │
│            │               │          │        │                   │               │ https://avd.aquasec.com/nvd/cve-2024-6119               │
├────────────┤               │          │        │                   │               │                                                         │
│ libssl3    │               │          │        │                   │               │                                                         │
│            │               │          │        │                   │               │                                                         │
│            │               │          │        │                   │               │                                                         │
└────────────┴───────────────┴──────────┴────────┴───────────────────┴───────────────┴─────────────────────────────────────────────────────────┘

2024-09-04 18:57 UTC, bryanpaget commented
The CVEs have been resolved:

```
pagetbr@l-pagetbr-3:~/workspace/projects/goofys$ trivy image goofys
2024-09-04T14:56:42-04:00	INFO	[vuln] Vulnerability scanning is enabled
2024-09-04T14:56:42-04:00	INFO	[secret] Secret scanning is enabled
2024-09-04T14:56:42-04:00	INFO	[secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-09-04T14:56:42-04:00	INFO	[secret] Please see also https://aquasecurity.github.io/trivy/v0.54/docs/scanner/secret#recommendation for faster secret detection
2024-09-04T14:56:42-04:00	INFO	Detected OS	family="alpine" version="3.20.2"
2024-09-04T14:56:42-04:00	INFO	[alpine] Detecting vulnerabilities...	os_version="3.20" repository="3.20" pkg_num=19
2024-09-04T14:56:42-04:00	INFO	Number of language-specific files	num=3
2024-09-04T14:56:42-04:00	INFO	[gobinary] Detecting vulnerabilities...

goofys (alpine 3.20.2)

Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

2024-09-09 18:03 UTC, Souheil-Yazji requested changes

2024-09-09 18:03 UTC, Souheil-Yazji commented on Dockerfile
> +FROM alpine:latest
pin tag

2024-09-09 18:37 UTC, bryanpaget reviewed
I've updated the Dockerfile to address the issues we discussed during the tech-elab review.

2024-09-09 18:37 UTC, bryanpaget commented on Dockerfile
> +FROM golang:1.23.0-alpine AS fusermount3-proxy-builder
revert to version 1.20.7

2024-09-09 18:37 UTC, bryanpaget commented on Dockerfile
> +FROM golang:1.23.0-alpine AS goofys-builder
revert to 1.20.7

2024-09-09 18:37 UTC, bryanpaget commented on Dockerfile
> +FROM alpine:latest
We are now using tag:3.20.3

2024-09-12 14:31 UTC, mathis-marcotte approved these changes
lgtm

2024-09-13 18:05 UTC, Souheil-Yazji approved these changes

2024-09-13 18:06 UTC, merged